title: "Programacion Web"
remote_theme: just-the-docs/just-the-docs
# theme: "just-the-docs"
search_enabled: false
logo: "/assets/images/logo.png"
heading_anchors: true

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Importante
    color: blue